pipeline {
    agent any

    stages {

        stage('Build Docker') {
            steps {
                sh 'cd SentimentStream && docker compose build'
            }
        }

        stage('Levantar servicios') {
            steps {
                sh 'cd SentimentStream && docker compose up -d'
            }
        }

        stage('Esperar servicios') {
            steps {
                sh 'sleep 10'
            }
        }

        stage('Test API') {
            steps {
                sh 'curl http://host.docker.internal:5000/sentiments'
            }
        }
    }
}
